//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.shared;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseRate" type="{urn:org:sample:hotel:shared}AmountType" minOccurs="0"/>
 *         &lt;element name="TaxRcAndFees" type="{urn:org:sample:hotel:shared}AmountType" minOccurs="0"/>
 *         &lt;element name="TotalRate" type="{urn:org:sample:hotel:shared}AmountType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceType", propOrder = {
    "baseRate",
    "taxRcAndFees",
    "totalRate"
})
public class PriceType {

    @XmlElement(name = "BaseRate")
    protected AmountType baseRate;
    @XmlElement(name = "TaxRcAndFees")
    protected AmountType taxRcAndFees;
    @XmlElement(name = "TotalRate", required = true)
    protected AmountType totalRate;

    /**
     * Gets the value of the baseRate property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getBaseRate() {
        return baseRate;
    }

    /**
     * Sets the value of the baseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setBaseRate(AmountType value) {
        this.baseRate = value;
    }

    /**
     * Gets the value of the taxRcAndFees property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTaxRcAndFees() {
        return taxRcAndFees;
    }

    /**
     * Sets the value of the taxRcAndFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTaxRcAndFees(AmountType value) {
        this.taxRcAndFees = value;
    }

    /**
     * Gets the value of the totalRate property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalRate() {
        return totalRate;
    }

    /**
     * Sets the value of the totalRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalRate(AmountType value) {
        this.totalRate = value;
    }

}
