//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.sample.hotel.shared.PriceType;
import org.sample.hotel.shared.PromotionType;


/**
 * <p>Java class for FeaturedOfferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeaturedOfferType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Price" type="{urn:org:sample:hotel:shared}PriceType"/>
 *         &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LengthOfStay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DetailsUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Promotion" type="{urn:org:sample:hotel:shared}PromotionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeaturedOfferType", propOrder = {
    "price",
    "checkInDate",
    "lengthOfStay",
    "detailsUrl",
    "promotion"
})
public class FeaturedOfferType {

    @XmlElement(name = "Price", required = true)
    protected PriceType price;
    @XmlElement(name = "CheckInDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar checkInDate;
    @XmlElement(name = "LengthOfStay")
    protected int lengthOfStay;
    @XmlElement(name = "DetailsUrl", required = true)
    protected String detailsUrl;
    @XmlElement(name = "Promotion")
    protected PromotionType promotion;

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the checkInDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckInDate() {
        return checkInDate;
    }

    /**
     * Sets the value of the checkInDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckInDate(XMLGregorianCalendar value) {
        this.checkInDate = value;
    }

    /**
     * Gets the value of the lengthOfStay property.
     * 
     */
    public int getLengthOfStay() {
        return lengthOfStay;
    }

    /**
     * Sets the value of the lengthOfStay property.
     * 
     */
    public void setLengthOfStay(int value) {
        this.lengthOfStay = value;
    }

    /**
     * Gets the value of the detailsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailsUrl() {
        return detailsUrl;
    }

    /**
     * Sets the value of the detailsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailsUrl(String value) {
        this.detailsUrl = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * @return
     *     possible object is
     *     {@link PromotionType }
     *     
     */
    public PromotionType getPromotion() {
        return promotion;
    }

    /**
     * Sets the value of the promotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromotionType }
     *     
     */
    public void setPromotion(PromotionType value) {
        this.promotion = value;
    }

}
