//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="description"/>
 *     &lt;enumeration value="address"/>
 *     &lt;enumeration value="geolocation"/>
 *     &lt;enumeration value="thumbnailurl"/>
 *     &lt;enumeration value="remainingcount"/>
 *     &lt;enumeration value="amenitylist"/>
 *     &lt;enumeration value="roomtypedescription"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldType")
@XmlEnum
public enum FieldType {


    /**
     * Hotel description field
     * 
     */
    @XmlEnumValue("description")
    DESCRIPTION("description"),

    /**
     * Hotel address, including
     * 						StreetAddress,City,Province,Country fields
     * 					
     * 
     */
    @XmlEnumValue("address")
    ADDRESS("address"),

    /**
     * Hotel geolocation, including Latitude,Longitude
     * 						fields
     * 					
     * 
     */
    @XmlEnumValue("geolocation")
    GEOLOCATION("geolocation"),

    /**
     * Hotel thumbnailUrl field
     * 
     */
    @XmlEnumValue("thumbnailurl")
    THUMBNAILURL("thumbnailurl"),

    /**
     * Hotel remaining room count field.
     * 					
     * 
     */
    @XmlEnumValue("remainingcount")
    REMAININGCOUNT("remainingcount"),

    /**
     * Hotel amenity list field.
     * 
     */
    @XmlEnumValue("amenitylist")
    AMENITYLIST("amenitylist"),

    /**
     * Room type description field.
     * 
     */
    @XmlEnumValue("roomtypedescription")
    ROOMTYPEDESCRIPTION("roomtypedescription");
    private final String value;

    FieldType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldType fromValue(String v) {
        for (FieldType c: FieldType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
