//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sample.hotel.shared.StayDatesType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeoLocation" type="{urn:org:sample:hotel:search}GeoLocationType" minOccurs="0"/>
 *         &lt;element name="Radius" type="{urn:org:sample:hotel:search}RadiusType" minOccurs="0"/>
 *         &lt;element name="HotelIdList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RegionIdList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RegionId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StayDates" type="{urn:org:sample:hotel:shared}StayDatesType" minOccurs="0"/>
 *         &lt;element name="UserCriteria" type="{urn:org:sample:hotel:search}UserCriteriaType" minOccurs="0"/>
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StarRating" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxHotelCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="QueryText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sort" type="{urn:org:sample:hotel:search}SortType" minOccurs="0"/>
 *         &lt;element name="Order" type="{urn:org:sample:hotel:search}OrderType" minOccurs="0"/>
 *         &lt;element name="ExcludeFieldList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Field" type="{urn:org:sample:hotel:search}FieldType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RecreationList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Recreation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoomCriteriaList" type="{urn:org:sample:hotel:search}RoomCriteriaListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geoLocation",
    "radius",
    "hotelIdList",
    "regionIdList",
    "stayDates",
    "userCriteria",
    "language",
    "currency",
    "starRating",
    "maxHotelCount",
    "queryText",
    "sort",
    "order",
    "excludeFieldList",
    "recreationList",
    "roomCriteriaList"
})
@XmlRootElement(name = "HotelSearchRequest")
public class HotelSearchRequest {

    @XmlElement(name = "GeoLocation")
    protected GeoLocationType geoLocation;
    @XmlElement(name = "Radius")
    protected RadiusType radius;
    @XmlElement(name = "HotelIdList")
    protected HotelSearchRequest.HotelIdList hotelIdList;
    @XmlElement(name = "RegionIdList")
    protected HotelSearchRequest.RegionIdList regionIdList;
    @XmlElement(name = "StayDates")
    protected StayDatesType stayDates;
    @XmlElement(name = "UserCriteria")
    protected UserCriteriaType userCriteria;
    @XmlElement(name = "Language")
    protected String language;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "StarRating")
    protected Float starRating;
    @XmlElement(name = "MaxHotelCount")
    protected Integer maxHotelCount;
    @XmlElement(name = "QueryText")
    protected String queryText;
    @XmlElement(name = "Sort")
    protected SortType sort;
    @XmlElement(name = "Order")
    protected OrderType order;
    @XmlElement(name = "ExcludeFieldList")
    protected HotelSearchRequest.ExcludeFieldList excludeFieldList;
    @XmlElement(name = "RecreationList")
    protected HotelSearchRequest.RecreationList recreationList;
    @XmlElement(name = "RoomCriteriaList")
    protected RoomCriteriaListType roomCriteriaList;

    /**
     * Gets the value of the geoLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocationType }
     *     
     */
    public GeoLocationType getGeoLocation() {
        return geoLocation;
    }

    /**
     * Sets the value of the geoLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocationType }
     *     
     */
    public void setGeoLocation(GeoLocationType value) {
        this.geoLocation = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link RadiusType }
     *     
     */
    public RadiusType getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadiusType }
     *     
     */
    public void setRadius(RadiusType value) {
        this.radius = value;
    }

    /**
     * Gets the value of the hotelIdList property.
     * 
     * @return
     *     possible object is
     *     {@link HotelSearchRequest.HotelIdList }
     *     
     */
    public HotelSearchRequest.HotelIdList getHotelIdList() {
        return hotelIdList;
    }

    /**
     * Sets the value of the hotelIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelSearchRequest.HotelIdList }
     *     
     */
    public void setHotelIdList(HotelSearchRequest.HotelIdList value) {
        this.hotelIdList = value;
    }

    /**
     * Gets the value of the regionIdList property.
     * 
     * @return
     *     possible object is
     *     {@link HotelSearchRequest.RegionIdList }
     *     
     */
    public HotelSearchRequest.RegionIdList getRegionIdList() {
        return regionIdList;
    }

    /**
     * Sets the value of the regionIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelSearchRequest.RegionIdList }
     *     
     */
    public void setRegionIdList(HotelSearchRequest.RegionIdList value) {
        this.regionIdList = value;
    }

    /**
     * Gets the value of the stayDates property.
     * 
     * @return
     *     possible object is
     *     {@link StayDatesType }
     *     
     */
    public StayDatesType getStayDates() {
        return stayDates;
    }

    /**
     * Sets the value of the stayDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayDatesType }
     *     
     */
    public void setStayDates(StayDatesType value) {
        this.stayDates = value;
    }

    /**
     * Gets the value of the userCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link UserCriteriaType }
     *     
     */
    public UserCriteriaType getUserCriteria() {
        return userCriteria;
    }

    /**
     * Sets the value of the userCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserCriteriaType }
     *     
     */
    public void setUserCriteria(UserCriteriaType value) {
        this.userCriteria = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the starRating property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStarRating() {
        return starRating;
    }

    /**
     * Sets the value of the starRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStarRating(Float value) {
        this.starRating = value;
    }

    /**
     * Gets the value of the maxHotelCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHotelCount() {
        return maxHotelCount;
    }

    /**
     * Sets the value of the maxHotelCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHotelCount(Integer value) {
        this.maxHotelCount = value;
    }

    /**
     * Gets the value of the queryText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryText() {
        return queryText;
    }

    /**
     * Sets the value of the queryText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryText(String value) {
        this.queryText = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link SortType }
     *     
     */
    public SortType getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortType }
     *     
     */
    public void setSort(SortType value) {
        this.sort = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link OrderType }
     *     
     */
    public OrderType getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderType }
     *     
     */
    public void setOrder(OrderType value) {
        this.order = value;
    }

    /**
     * Gets the value of the excludeFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link HotelSearchRequest.ExcludeFieldList }
     *     
     */
    public HotelSearchRequest.ExcludeFieldList getExcludeFieldList() {
        return excludeFieldList;
    }

    /**
     * Sets the value of the excludeFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelSearchRequest.ExcludeFieldList }
     *     
     */
    public void setExcludeFieldList(HotelSearchRequest.ExcludeFieldList value) {
        this.excludeFieldList = value;
    }

    /**
     * Gets the value of the recreationList property.
     * 
     * @return
     *     possible object is
     *     {@link HotelSearchRequest.RecreationList }
     *     
     */
    public HotelSearchRequest.RecreationList getRecreationList() {
        return recreationList;
    }

    /**
     * Sets the value of the recreationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelSearchRequest.RecreationList }
     *     
     */
    public void setRecreationList(HotelSearchRequest.RecreationList value) {
        this.recreationList = value;
    }

    /**
     * Gets the value of the roomCriteriaList property.
     * 
     * @return
     *     possible object is
     *     {@link RoomCriteriaListType }
     *     
     */
    public RoomCriteriaListType getRoomCriteriaList() {
        return roomCriteriaList;
    }

    /**
     * Sets the value of the roomCriteriaList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomCriteriaListType }
     *     
     */
    public void setRoomCriteriaList(RoomCriteriaListType value) {
        this.roomCriteriaList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Field" type="{urn:org:sample:hotel:search}FieldType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class ExcludeFieldList {

        @XmlElement(name = "Field", required = true)
        protected List<FieldType> field;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldType }
         * 
         * 
         */
        public List<FieldType> getField() {
            if (field == null) {
                field = new ArrayList<FieldType>();
            }
            return this.field;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotelId"
    })
    public static class HotelIdList {

        @XmlElement(name = "HotelId", type = Integer.class)
        protected List<Integer> hotelId;

        /**
         * Gets the value of the hotelId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hotelId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotelId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getHotelId() {
            if (hotelId == null) {
                hotelId = new ArrayList<Integer>();
            }
            return this.hotelId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Recreation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recreation"
    })
    public static class RecreationList {

        @XmlElement(name = "Recreation", required = true)
        protected List<String> recreation;

        /**
         * Gets the value of the recreation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recreation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecreation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRecreation() {
            if (recreation == null) {
                recreation = new ArrayList<String>();
            }
            return this.recreation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RegionId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regionId"
    })
    public static class RegionIdList {

        @XmlElement(name = "RegionId", type = Integer.class)
        protected List<Integer> regionId;

        /**
         * Gets the value of the regionId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the regionId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRegionId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getRegionId() {
            if (regionId == null) {
                regionId = new ArrayList<Integer>();
            }
            return this.regionId;
        }

    }

}
