//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.sample.hotel.shared.AmenityListType;
import org.sample.hotel.shared.AmountType;
import org.sample.hotel.shared.PriceType;
import org.sample.hotel.shared.PromotionType;


/**
 * <p>Java class for HotelInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HComHotelID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Location" type="{urn:org:sample:hotel:search}HotelLocationType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FeaturedOffer" type="{urn:org:sample:hotel:search}FeaturedOfferType" minOccurs="0"/>
 *         &lt;element name="Price" type="{urn:org:sample:hotel:shared}PriceType" minOccurs="0"/>
 *         &lt;element name="HotelMandatoryTaxesAndFees" type="{urn:org:sample:hotel:shared}AmountType" minOccurs="0"/>
 *         &lt;element name="Promotion" type="{urn:org:sample:hotel:shared}PromotionType" minOccurs="0"/>
 *         &lt;element name="DetailsUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateDetailsUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StarRating" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ThumbnailUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GuestRating" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="RoomTypeList" type="{urn:org:sample:hotel:search}RoomTypeListType" minOccurs="0"/>
 *         &lt;element name="AmenityList" type="{urn:org:sample:hotel:shared}AmenityListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelInfoType", propOrder = {
    "hotelID",
    "hComHotelID",
    "name",
    "location",
    "description",
    "statusCode",
    "statusDescription",
    "featuredOffer",
    "price",
    "hotelMandatoryTaxesAndFees",
    "promotion",
    "detailsUrl",
    "rateDetailsUrl",
    "starRating",
    "thumbnailUrl",
    "guestRating",
    "roomTypeList",
    "amenityList"
})
public class HotelInfoType {

    @XmlElement(name = "HotelID")
    protected int hotelID;
    @XmlElement(name = "HComHotelID")
    protected Integer hComHotelID;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Location", required = true)
    protected HotelLocationType location;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "StatusCode")
    protected Integer statusCode;
    @XmlElement(name = "StatusDescription")
    protected String statusDescription;
    @XmlElement(name = "FeaturedOffer")
    protected FeaturedOfferType featuredOffer;
    @XmlElement(name = "Price")
    protected PriceType price;
    @XmlElement(name = "HotelMandatoryTaxesAndFees")
    protected AmountType hotelMandatoryTaxesAndFees;
    @XmlElement(name = "Promotion")
    protected PromotionType promotion;
    @XmlElement(name = "DetailsUrl")
    protected String detailsUrl;
    @XmlElement(name = "RateDetailsUrl")
    protected String rateDetailsUrl;
    @XmlElement(name = "StarRating")
    protected Float starRating;
    @XmlElement(name = "ThumbnailUrl")
    protected String thumbnailUrl;
    @XmlElement(name = "GuestRating")
    protected Float guestRating;
    @XmlElement(name = "RoomTypeList")
    protected RoomTypeListType roomTypeList;
    @XmlElement(name = "AmenityList")
    protected AmenityListType amenityList;

    /**
     * Gets the value of the hotelID property.
     * 
     */
    public int getHotelID() {
        return hotelID;
    }

    /**
     * Sets the value of the hotelID property.
     * 
     */
    public void setHotelID(int value) {
        this.hotelID = value;
    }

    /**
     * Gets the value of the hComHotelID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHComHotelID() {
        return hComHotelID;
    }

    /**
     * Sets the value of the hComHotelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHComHotelID(Integer value) {
        this.hComHotelID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link HotelLocationType }
     *     
     */
    public HotelLocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelLocationType }
     *     
     */
    public void setLocation(HotelLocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatusCode(Integer value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDescription() {
        return statusDescription;
    }

    /**
     * Sets the value of the statusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

    /**
     * Gets the value of the featuredOffer property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturedOfferType }
     *     
     */
    public FeaturedOfferType getFeaturedOffer() {
        return featuredOffer;
    }

    /**
     * Sets the value of the featuredOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturedOfferType }
     *     
     */
    public void setFeaturedOffer(FeaturedOfferType value) {
        this.featuredOffer = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the hotelMandatoryTaxesAndFees property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getHotelMandatoryTaxesAndFees() {
        return hotelMandatoryTaxesAndFees;
    }

    /**
     * Sets the value of the hotelMandatoryTaxesAndFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setHotelMandatoryTaxesAndFees(AmountType value) {
        this.hotelMandatoryTaxesAndFees = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * @return
     *     possible object is
     *     {@link PromotionType }
     *     
     */
    public PromotionType getPromotion() {
        return promotion;
    }

    /**
     * Sets the value of the promotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromotionType }
     *     
     */
    public void setPromotion(PromotionType value) {
        this.promotion = value;
    }

    /**
     * Gets the value of the detailsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailsUrl() {
        return detailsUrl;
    }

    /**
     * Sets the value of the detailsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailsUrl(String value) {
        this.detailsUrl = value;
    }

    /**
     * Gets the value of the rateDetailsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDetailsUrl() {
        return rateDetailsUrl;
    }

    /**
     * Sets the value of the rateDetailsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDetailsUrl(String value) {
        this.rateDetailsUrl = value;
    }

    /**
     * Gets the value of the starRating property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStarRating() {
        return starRating;
    }

    /**
     * Sets the value of the starRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStarRating(Float value) {
        this.starRating = value;
    }

    /**
     * Gets the value of the thumbnailUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * Sets the value of the thumbnailUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnailUrl(String value) {
        this.thumbnailUrl = value;
    }

    /**
     * Gets the value of the guestRating property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGuestRating() {
        return guestRating;
    }

    /**
     * Sets the value of the guestRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGuestRating(Float value) {
        this.guestRating = value;
    }

    /**
     * Gets the value of the roomTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link RoomTypeListType }
     *     
     */
    public RoomTypeListType getRoomTypeList() {
        return roomTypeList;
    }

    /**
     * Sets the value of the roomTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomTypeListType }
     *     
     */
    public void setRoomTypeList(RoomTypeListType value) {
        this.roomTypeList = value;
    }

    /**
     * Gets the value of the amenityList property.
     * 
     * @return
     *     possible object is
     *     {@link AmenityListType }
     *     
     */
    public AmenityListType getAmenityList() {
        return amenityList;
    }

    /**
     * Sets the value of the amenityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmenityListType }
     *     
     */
    public void setAmenityList(AmenityListType value) {
        this.amenityList = value;
    }

}
