//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sample.hotel.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sample.hotel.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserCriteriaType }
     * 
     */
    public UserCriteriaType createUserCriteriaType() {
        return new UserCriteriaType();
    }

    /**
     * Create an instance of {@link HotelSearchResponse }
     * 
     */
    public HotelSearchResponse createHotelSearchResponse() {
        return new HotelSearchResponse();
    }

    /**
     * Create an instance of {@link HotelSearchFault }
     * 
     */
    public HotelSearchFault createHotelSearchFault() {
        return new HotelSearchFault();
    }

    /**
     * Create an instance of {@link HotelSearchRequest.HotelIdList }
     * 
     */
    public HotelSearchRequest.HotelIdList createHotelSearchRequestHotelIdList() {
        return new HotelSearchRequest.HotelIdList();
    }

    /**
     * Create an instance of {@link RoomCriteriaListType }
     * 
     */
    public RoomCriteriaListType createRoomCriteriaListType() {
        return new RoomCriteriaListType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link HotelSearchRequest.RegionIdList }
     * 
     */
    public HotelSearchRequest.RegionIdList createHotelSearchRequestRegionIdList() {
        return new HotelSearchRequest.RegionIdList();
    }

    /**
     * Create an instance of {@link HotelSearchRequest }
     * 
     */
    public HotelSearchRequest createHotelSearchRequest() {
        return new HotelSearchRequest();
    }

    /**
     * Create an instance of {@link HotelLocationType }
     * 
     */
    public HotelLocationType createHotelLocationType() {
        return new HotelLocationType();
    }

    /**
     * Create an instance of {@link RoomTypeType }
     * 
     */
    public RoomTypeType createRoomTypeType() {
        return new RoomTypeType();
    }

    /**
     * Create an instance of {@link HotelInfoType }
     * 
     */
    public HotelInfoType createHotelInfoType() {
        return new HotelInfoType();
    }

    /**
     * Create an instance of {@link RoomAmenityType }
     * 
     */
    public RoomAmenityType createRoomAmenityType() {
        return new RoomAmenityType();
    }

    /**
     * Create an instance of {@link HotelSearchRequest.ExcludeFieldList }
     * 
     */
    public HotelSearchRequest.ExcludeFieldList createHotelSearchRequestExcludeFieldList() {
        return new HotelSearchRequest.ExcludeFieldList();
    }

    /**
     * Create an instance of {@link RoomTypeListType }
     * 
     */
    public RoomTypeListType createRoomTypeListType() {
        return new RoomTypeListType();
    }

    /**
     * Create an instance of {@link GeoLocationType }
     * 
     */
    public GeoLocationType createGeoLocationType() {
        return new GeoLocationType();
    }

    /**
     * Create an instance of {@link RadiusType }
     * 
     */
    public RadiusType createRadiusType() {
        return new RadiusType();
    }

    /**
     * Create an instance of {@link HotelSearchRequest.RecreationList }
     * 
     */
    public HotelSearchRequest.RecreationList createHotelSearchRequestRecreationList() {
        return new HotelSearchRequest.RecreationList();
    }

    /**
     * Create an instance of {@link FeaturedOfferType }
     * 
     */
    public FeaturedOfferType createFeaturedOfferType() {
        return new FeaturedOfferType();
    }

    /**
     * Create an instance of {@link RoomAmenityListType }
     * 
     */
    public RoomAmenityListType createRoomAmenityListType() {
        return new RoomAmenityListType();
    }

    /**
     * Create an instance of {@link ErrorListType }
     * 
     */
    public ErrorListType createErrorListType() {
        return new ErrorListType();
    }

    /**
     * Create an instance of {@link HotelInfoListType }
     * 
     */
    public HotelInfoListType createHotelInfoListType() {
        return new HotelInfoListType();
    }

}
