//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.sample.hotel.shared.AmountType;
import org.sample.hotel.shared.PriceType;
import org.sample.hotel.shared.PromotionType;


/**
 * <p>Java class for RoomTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoomTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemainingCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Price" type="{urn:org:sample:hotel:shared}PriceType" minOccurs="0"/>
 *         &lt;element name="Promotion" type="{urn:org:sample:hotel:shared}PromotionType" minOccurs="0"/>
 *         &lt;element name="HotelMandatoryTaxesAndFees" type="{urn:org:sample:hotel:shared}AmountType" minOccurs="0"/>
 *         &lt;element name="RateDetailsUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomAmenityList" type="{urn:org:sample:hotel:search}RoomAmenityListType" minOccurs="0"/>
 *         &lt;element name="Refundable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoomTypeType", propOrder = {
    "description",
    "remainingCount",
    "price",
    "promotion",
    "hotelMandatoryTaxesAndFees",
    "rateDetailsUrl",
    "roomAmenityList",
    "refundable"
})
public class RoomTypeType {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "RemainingCount")
    protected Integer remainingCount;
    @XmlElement(name = "Price")
    protected PriceType price;
    @XmlElement(name = "Promotion")
    protected PromotionType promotion;
    @XmlElement(name = "HotelMandatoryTaxesAndFees")
    protected AmountType hotelMandatoryTaxesAndFees;
    @XmlElement(name = "RateDetailsUrl")
    protected String rateDetailsUrl;
    @XmlElement(name = "RoomAmenityList")
    protected RoomAmenityListType roomAmenityList;
    @XmlElement(name = "Refundable")
    protected boolean refundable;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remainingCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRemainingCount() {
        return remainingCount;
    }

    /**
     * Sets the value of the remainingCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRemainingCount(Integer value) {
        this.remainingCount = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * @return
     *     possible object is
     *     {@link PromotionType }
     *     
     */
    public PromotionType getPromotion() {
        return promotion;
    }

    /**
     * Sets the value of the promotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromotionType }
     *     
     */
    public void setPromotion(PromotionType value) {
        this.promotion = value;
    }

    /**
     * Gets the value of the hotelMandatoryTaxesAndFees property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getHotelMandatoryTaxesAndFees() {
        return hotelMandatoryTaxesAndFees;
    }

    /**
     * Sets the value of the hotelMandatoryTaxesAndFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setHotelMandatoryTaxesAndFees(AmountType value) {
        this.hotelMandatoryTaxesAndFees = value;
    }

    /**
     * Gets the value of the rateDetailsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDetailsUrl() {
        return rateDetailsUrl;
    }

    /**
     * Sets the value of the rateDetailsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDetailsUrl(String value) {
        this.rateDetailsUrl = value;
    }

    /**
     * Gets the value of the roomAmenityList property.
     * 
     * @return
     *     possible object is
     *     {@link RoomAmenityListType }
     *     
     */
    public RoomAmenityListType getRoomAmenityList() {
        return roomAmenityList;
    }

    /**
     * Sets the value of the roomAmenityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomAmenityListType }
     *     
     */
    public void setRoomAmenityList(RoomAmenityListType value) {
        this.roomAmenityList = value;
    }

    /**
     * Gets the value of the refundable property.
     * 
     */
    public boolean isRefundable() {
        return refundable;
    }

    /**
     * Sets the value of the refundable property.
     * 
     */
    public void setRefundable(boolean value) {
        this.refundable = value;
    }

}
