//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SortType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SortType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="price"/>
 *     &lt;enumeration value="starrating"/>
 *     &lt;enumeration value="guestrating"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SortType")
@XmlEnum
public enum SortType {

    @XmlEnumValue("price")
    PRICE("price"),
    @XmlEnumValue("starrating")
    STARRATING("starrating"),
    @XmlEnumValue("guestrating")
    GUESTRATING("guestrating");
    private final String value;

    SortType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SortType fromValue(String v) {
        for (SortType c: SortType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
