//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:23:48 AM CST 
//


package org.sample.hotel.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserCriteriaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HComHotelID" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LowestPriceOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AvailableOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DeeplinkMode" type="{urn:org:sample:hotel:search}DeeplinkType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserCriteriaType", propOrder = {
    "hComHotelID",
    "lowestPriceOnly",
    "availableOnly",
    "deeplinkMode"
})
public class UserCriteriaType {

    @XmlElement(name = "HComHotelID")
    protected Boolean hComHotelID;
    @XmlElement(name = "LowestPriceOnly")
    protected Boolean lowestPriceOnly;
    @XmlElement(name = "AvailableOnly")
    protected Boolean availableOnly;
    @XmlElement(name = "DeeplinkMode")
    protected DeeplinkType deeplinkMode;

    /**
     * Gets the value of the hComHotelID property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHComHotelID() {
        return hComHotelID;
    }

    /**
     * Sets the value of the hComHotelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHComHotelID(Boolean value) {
        this.hComHotelID = value;
    }

    /**
     * Gets the value of the lowestPriceOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLowestPriceOnly() {
        return lowestPriceOnly;
    }

    /**
     * Sets the value of the lowestPriceOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLowestPriceOnly(Boolean value) {
        this.lowestPriceOnly = value;
    }

    /**
     * Gets the value of the availableOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvailableOnly() {
        return availableOnly;
    }

    /**
     * Sets the value of the availableOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvailableOnly(Boolean value) {
        this.availableOnly = value;
    }

    /**
     * Gets the value of the deeplinkMode property.
     * 
     * @return
     *     possible object is
     *     {@link DeeplinkType }
     *     
     */
    public DeeplinkType getDeeplinkMode() {
        return deeplinkMode;
    }

    /**
     * Sets the value of the deeplinkMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeeplinkType }
     *     
     */
    public void setDeeplinkMode(DeeplinkType value) {
        this.deeplinkMode = value;
    }

}
